#이름을 잘못 입력시, 오류가 발생합니다
#생성할때, '값'동안 기다림 (사용안함 = 0)
wait_seconds : 0
#생성될 월드
world : world
#맨 밑부분에 들어가는 블록
create_block : oak_fence
#전체 비율의 각각의%
ord_spawn:
  stone : 50
  coal_ore : 10
  iron_ore : 10
  copper_ore : 10
  redstone_ore : 10
  gold_ore : 8
  diamond_ore : 1
  emerald_ore : 1
  diamond_block : 0.1